{% set name = "backports-datetime-fromisoformat" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backports-datetime-fromisoformat-{{ version }}.tar.gz
  sha256: 1afaa4d593471a3b9a9875cc9b7edf2df8a4f317679ea658a8f8fa255539ce90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python  >=3.7
    - pip
  run:
    - python  >=3.7

test:
  imports:
    - backports.datetime_fromisoformat
  commands:
    - pip check
  requires:
    # to make sure we're actually testing the backport
    - python <3.11
    - pip

about:
  home: https://github.com/movermeyer/backports.datetime_fromisoformat
  summary: Backport of Python 3.11's datetime.fromisoformat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/movermeyer/backports.datetime_fromisoformat
  doc_url: https://github.com/movermeyer/backports.datetime_fromisoformat/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
