{% set name = "backports-datetime-fromisoformat" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 142313bde1f93b0ea55f20f5a6ea034f84c79713daeb252dc47d40019db3812f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [py<=311]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [py<=311]
    - {{ stdlib("c") }}  # [py<=311]
  host:
    # so python > 3.11 don't get removed 
    - python
    - pip  # [py<=311]
    - setuptools  # [py<=311]
  run:
    - python

test:
  imports:
    - backports.datetime_fromisoformat   # [py<=311]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/movermeyer/backports.datetime_fromisoformat
  summary: Backport of Python 3.11's datetime.fromisoformat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/movermeyer/backports.datetime_fromisoformat
  doc_url: https://github.com/movermeyer/backports.datetime_fromisoformat/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
